name: "MyAnimeList readme workflow"
author: "Gamersindo1223"
description: "Puts your newest activity from MyAnimeList into your readme"

inputs:
    username:
        description: "Your MAL user username"
        default: ""
        required: true

    gh_token:
        description: "GitHub access token with Repo scope"
        default: ${{ github.token }}
        required: true

    readme_path:
        description: "Path of the readme file you want to update"
        default: ""
        required: true

    branch:
        description: "Branch of the README.md"
        default: "main"
        required: false
    limit:
        description: "Limit of history that will be showed"
        default: "10"
        required: false

runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - name: cloning MAL-autoreadme
          run: git clone https://github.com/gamersindo1223/MAL-ReadmeList
          shell: bash
        - name: Set Node.js 18
          uses: actions/setup-node@v3
          with:
               node-version: 18
        - name: Install dependencies
          working-directory: ./MAL-autoreadme
          run: npm i
          shell: bash
        - name: Run the script
          working-directory: ./MAL-autoreadme
          run: node index.mjs
          shell: bash
          env: 
              username: ${{ inputs.username }}
              gh_token: ${{ inputs.gh_token }}
              malkey: ${{ var.malkey }}
              readme_path: ${{ inputs.readme_path }}
              branch: ${{ inputs.branch }}
              limit: ${{ inputs.limit }}